In [24]:
import pandas as pd
import numpy as np
import seaborn as sns

In [14]:
df= pd.read_csv(r"C:\Users\Brian\Desktop\arvo424.csv")

In [15]:
df.head()

,PT,Reading,Eye,Disc Anom-N,VCDR-N,DR?-N,DR#-N,Exudate-N,Exu#-N,Micro-A_N,MicroA#-N,Hemmhorrage -N,Hem#-N
0,FFL003X,Nx,OS,0.01,0.38,Normal,0,Absent,0,Absent,0,Absent,0
1,FFL003X,Nx,OD,0.01,0.38,Mild,1,Absent,0,Absent,0,Absent,0
2,FFL034F,Nx,OD,0.01,0.24,Mild,1,Absent,0,Absent,0,Absent,0
3,FFL034F,Nx,OS,0.01,0.27,Mild,1,Absent,0,Absent,0,Absent,0
4,FFL059F,Nx,OD,0.01,0.41,Mild,1,Absent,0,Absent,0,Absent,0

In [16]:
len(df)

236

In [22]:
df.describe()

       Disc Anom-N      VCDR-N       DR#-N      Exu#-N   MicroA#-N      Hem#-N
count   232.000000  232.000000  236.000000  236.000000  236.000000  236.000000
mean      0.395647    0.322974    0.419492    0.038136    0.334746    0.038136
std       0.440536    0.124522    0.637383    0.191931    0.472904    0.191931
min       0.010000    0.010000    0.000000    0.000000    0.000000    0.000000
25%       0.010000    0.230000    0.000000    0.000000    0.000000    0.000000
50%       0.035000    0.305000    0.000000    0.000000    0.000000    0.000000
75%       0.952500    0.382500    1.000000    0.000000    1.000000    0.000000
max       1.000000    0.670000    3.000000    1.000000    1.000000    1.000000

In [19]:
df.isna().sum()

PT                0
Reading           0
Eye               0
Disc Anom-N       4
VCDR-N            4
DR?-N             5
DR#-N             0
Exudate-N         0
Exu#-N            0
Micro-A_N         0
MicroA#-N         0
Hemmhorrage -N    0
Hem#-N            0
dtype: int64